name: On PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: ["main"]

permissions:
  checks: write
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/call-pre-commit.yml
    secrets: inherit

  build-ubuntu:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/call-build-ubuntu.yml
    secrets: inherit

  build-macos:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/call-build-macos.yml
    secrets: inherit

  test-sim:
    if: github.event.pull_request.draft == false
    needs: [build-ubuntu, build-macos]
    uses: ./.github/workflows/call-test-sim.yml
    secrets: inherit

  check-all-green:
    if: always()
    needs:
      - pre-commit
      - build-ubuntu
      - build-macos
      - test-sim
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether all needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: build-ubuntu, build-macos, test-sim
          jobs: ${{ toJSON(needs) }}
